language: python
sudo: false
python:
- 3.7
script: py.test -v
services:
  - docker
before_install:
  - docker pull postgres
  - docker pull mariadb
  - docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=docker -d postgres
  - docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=docker -d mariadb