language: python
sudo: false
python:
  - "3.6"
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
services:
  - docker
before_install:
  - docker pull postgres
  - docker pull mariadb
  - docker run -d -p 55432:5432 -e POSTGRES_PASSWORD=docker -d postgres
  - docker run -d -p 33306:3306 -e MYSQL_ROOT_PASSWORD=docker -d mariadb
install:
  - pip install pipenv
  - pipenv sync
  - pipenv shell
  - pipenv install --dev